/*
Generated by cue.

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: no version
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package init_container

import (
	"encoding/json"

	"vela-go-sdk/apis/utils"
)

// checks if the InitContainerSpecExtraVolumeMounts type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &InitContainerSpecExtraVolumeMounts{}

// InitContainerSpecExtraVolumeMounts struct for InitContainerSpecExtraVolumeMounts
type InitContainerSpecExtraVolumeMounts struct {
	// The mountPath for mount in the init container
	mountPath string `json:"mountPath"`
	// The name of the volume to be mounted
	name string `json:"name"`
}

// InitContainerSpecExtraVolumeMountsWith instantiates a new InitContainerSpecExtraVolumeMounts object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func InitContainerSpecExtraVolumeMountsWith(mountPath string, name string) *InitContainerSpecExtraVolumeMounts {
	this := InitContainerSpecExtraVolumeMounts{}
	this.mountPath = mountPath
	this.name = name
	return &this
}

// NewInitContainerSpecExtraVolumeMounts instantiates a new InitContainerSpecExtraVolumeMounts object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInitContainerSpecExtraVolumeMounts() *InitContainerSpecExtraVolumeMounts {
	this := InitContainerSpecExtraVolumeMounts{}
	return &this
}

// GetMountPath returns the MountPath field value
func (o *InitContainerSpecExtraVolumeMounts) GetMountPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.mountPath
}

// GetMountPathOk returns a tuple with the MountPath field value
// and a boolean to check if the value has been set.
func (o *InitContainerSpecExtraVolumeMounts) GetMountPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.mountPath, true
}

// MountPath sets field value
func (o *InitContainerSpecExtraVolumeMounts) MountPath(v string) *InitContainerSpecExtraVolumeMounts {
	o.mountPath = v
	return o
}

// GetName returns the Name field value
func (o *InitContainerSpecExtraVolumeMounts) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *InitContainerSpecExtraVolumeMounts) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.name, true
}

// Name sets field value
func (o *InitContainerSpecExtraVolumeMounts) Name(v string) *InitContainerSpecExtraVolumeMounts {
	o.name = v
	return o
}

func (o InitContainerSpecExtraVolumeMounts) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InitContainerSpecExtraVolumeMounts) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["mountPath"] = o.mountPath
	toSerialize["name"] = o.name
	return toSerialize, nil
}

type NullableInitContainerSpecExtraVolumeMounts struct {
	value *InitContainerSpecExtraVolumeMounts
	isSet bool
}

func (v NullableInitContainerSpecExtraVolumeMounts) Get() *InitContainerSpecExtraVolumeMounts {
	return v.value
}

func (v *NullableInitContainerSpecExtraVolumeMounts) Set(val *InitContainerSpecExtraVolumeMounts) {
	v.value = val
	v.isSet = true
}

func (v NullableInitContainerSpecExtraVolumeMounts) IsSet() bool {
	return v.isSet
}

func (v *NullableInitContainerSpecExtraVolumeMounts) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInitContainerSpecExtraVolumeMounts(val *InitContainerSpecExtraVolumeMounts) *NullableInitContainerSpecExtraVolumeMounts {
	return &NullableInitContainerSpecExtraVolumeMounts{value: val, isSet: true}
}

func (v NullableInitContainerSpecExtraVolumeMounts) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInitContainerSpecExtraVolumeMounts) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
