/*
Generated by cue.

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: no version
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package override

import (
	"encoding/json"

	"github.com/oam-dev/kubevela-core-api/apis/core.oam.dev/v1beta1"
	"github.com/oam-dev/kubevela-core-api/pkg/oam/util"

	"github.com/chivalryq/vela-go-sdk/pkg/apis"
	sdkcommon "github.com/chivalryq/vela-go-sdk/pkg/apis/common"
	"github.com/chivalryq/vela-go-sdk/pkg/apis/utils"
)

// checks if the OverrideSpec type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &OverrideSpec{}

// OverrideSpec struct for OverrideSpec
type OverrideSpec struct {
	// Specify the overridden component configuration.
	components []PatchParams `json:"components"`
	// Specify a list of component names to use, if empty, all components will be selected.
	selector []string `json:"selector,omitempty"`
}

// NewOverrideSpecWith instantiates a new OverrideSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOverrideSpecWith(components []PatchParams) *OverrideSpec {
	this := OverrideSpec{}
	this.components = components
	return &this
}

// NewOverrideSpec instantiates a new OverrideSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOverrideSpec() *OverrideSpec {
	this := OverrideSpec{}
	return &this
}

// GetComponents returns the Components field value
func (o *OverridePolicy) GetComponents() []PatchParams {
	if o == nil {
		var ret []PatchParams
		return ret
	}

	return o.Properties.components
}

// GetComponentsOk returns a tuple with the Components field value
// and a boolean to check if the value has been set.
func (o *OverridePolicy) GetComponentsOk() ([]PatchParams, bool) {
	if o == nil {
		return nil, false
	}
	return o.Properties.components, true
}

// Components sets field value
func (o *OverridePolicy) Components(v []PatchParams) *OverridePolicy {
	o.Properties.components = v
	return o
}

// GetSelector returns the Selector field value if set, zero value otherwise.
func (o *OverridePolicy) GetSelector() []string {
	if o == nil || utils.IsNil(o.Properties.selector) {
		var ret []string
		return ret
	}
	return o.Properties.selector
}

// GetSelectorOk returns a tuple with the Selector field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OverridePolicy) GetSelectorOk() ([]string, bool) {
	if o == nil || utils.IsNil(o.Properties.selector) {
		return nil, false
	}
	return o.Properties.selector, true
}

// HasSelector returns a boolean if a field has been set.
func (o *OverridePolicy) HasSelector() bool {
	if o != nil && !utils.IsNil(o.Properties.selector) {
		return true
	}

	return false
}

// Selector gets a reference to the given []string and assigns it to the selector field.
// selector:  Specify a list of component names to use, if empty, all components will be selected.
func (o *OverridePolicy) Selector(v []string) *OverridePolicy {
	o.Properties.selector = v
	return o
}

func (o OverrideSpec) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OverrideSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["components"] = o.components
	if !utils.IsNil(o.selector) {
		toSerialize["selector"] = o.selector
	}
	return toSerialize, nil
}

type NullableOverrideSpec struct {
	value *OverrideSpec
	isSet bool
}

func (v NullableOverrideSpec) Get() *OverrideSpec {
	return v.value
}

func (v *NullableOverrideSpec) Set(val *OverrideSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableOverrideSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableOverrideSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOverrideSpec(val *OverrideSpec) *NullableOverrideSpec {
	return &NullableOverrideSpec{value: val, isSet: true}
}

func (v NullableOverrideSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOverrideSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

const OverrideType = "override"

func init() {
	sdkcommon.RegisterPolicy(OverrideType, FromPolicy)
}

type OverridePolicy struct {
	Base       apis.PolicyBase
	Properties OverrideSpec
}

func Override(name string) *OverridePolicy {
	o := &OverridePolicy{Base: apis.PolicyBase{
		Name: name,
	}}
	return o
}

func (o *OverridePolicy) Build() v1beta1.AppPolicy {
	res := v1beta1.AppPolicy{
		Name:       o.Base.Name,
		Properties: util.Object2RawExtension(o.Properties),
		Type:       OverrideType,
	}
	return res
}

func (o *OverridePolicy) FromPolicy(from v1beta1.AppPolicy) (*OverridePolicy, error) {
	var properties OverrideSpec
	if from.Properties != nil {
		err := json.Unmarshal(from.Properties.Raw, &properties)
		if err != nil {
			return nil, err
		}
	}
	o.Base.Name = from.Name
	o.Properties = properties
	return o, nil
}

func FromPolicy(from v1beta1.AppPolicy) (apis.Policy, error) {
	o := &OverridePolicy{}
	return o.FromPolicy(from)
}

func (o *OverridePolicy) DefType() string {
	return OverrideType
}
