/*
Generated by cue.

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: no version
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nocalhost

import (
	"encoding/json"

	"vela-go-sdk/pkg/apis/utils"
)

// checks if the Sync type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Sync{}

// Sync struct for Sync
type Sync struct {
	filePattern       []string `json:"filePattern"`
	ignoreFilePattern []string `json:"ignoreFilePattern"`
	type_             string   `json:"type"`
}

// NewSyncWith instantiates a new Sync object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSyncWith(filePattern []string, ignoreFilePattern []string, type_ string) *Sync {
	this := Sync{}
	this.filePattern = filePattern
	this.ignoreFilePattern = ignoreFilePattern
	this.type_ = type_
	return &this
}

// NewSync instantiates a new Sync object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSync() *Sync {
	this := Sync{}
	var type_ string = "send"
	this.type_ = type_
	return &this
}

// GetFilePattern returns the FilePattern field value
func (o *Sync) GetFilePattern() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.filePattern
}

// GetFilePatternOk returns a tuple with the FilePattern field value
// and a boolean to check if the value has been set.
func (o *Sync) GetFilePatternOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.filePattern, true
}

// FilePattern sets field value
func (o *Sync) FilePattern(v []string) *Sync {
	o.filePattern = v
	return o
}

// GetIgnoreFilePattern returns the IgnoreFilePattern field value
func (o *Sync) GetIgnoreFilePattern() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.ignoreFilePattern
}

// GetIgnoreFilePatternOk returns a tuple with the IgnoreFilePattern field value
// and a boolean to check if the value has been set.
func (o *Sync) GetIgnoreFilePatternOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ignoreFilePattern, true
}

// IgnoreFilePattern sets field value
func (o *Sync) IgnoreFilePattern(v []string) *Sync {
	o.ignoreFilePattern = v
	return o
}

// GetType returns the Type field value
func (o *Sync) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.type_
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *Sync) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.type_, true
}

// Type sets field value
func (o *Sync) Type(v string) *Sync {
	o.type_ = v
	return o
}

func (o Sync) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Sync) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["filePattern"] = o.filePattern
	toSerialize["ignoreFilePattern"] = o.ignoreFilePattern
	toSerialize["type"] = o.type_
	return toSerialize, nil
}

type NullableSync struct {
	value *Sync
	isSet bool
}

func (v NullableSync) Get() *Sync {
	return v.value
}

func (v *NullableSync) Set(val *Sync) {
	v.value = val
	v.isSet = true
}

func (v NullableSync) IsSet() bool {
	return v.isSet
}

func (v *NullableSync) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSync(val *Sync) *NullableSync {
	return &NullableSync{value: val, isSet: true}
}

func (v NullableSync) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSync) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
