/*
Generated by cue.

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: no version
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package print_message_in_status

import (
"encoding/json"
. "vela-go-sdk/api"
"vela-go-sdk/apis/utils"

"github.com/oam-dev/kubevela-core-api/apis/core.oam.dev/common"
"github.com/oam-dev/kubevela-core-api/pkg/oam/util"
)



    
    // checks if the PrintMessageInStatusSpec type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &PrintMessageInStatusSpec{}

// PrintMessageInStatusSpec struct for PrintMessageInStatusSpec
type PrintMessageInStatusSpec struct {
	message string `json:"message"`
}

// NewPrintMessageInStatusSpec instantiates a new PrintMessageInStatusSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrintMessageInStatusSpec(message string) *PrintMessageInStatusSpec {
	this := PrintMessageInStatusSpec{}
	this.message = message
	return &this
}

// NewPrintMessageInStatusSpecWithDefaults instantiates a new PrintMessageInStatusSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrintMessageInStatusSpecWithDefaults() *PrintMessageInStatusSpec {
	this := PrintMessageInStatusSpec{}
	return &this
}

// GetMessage returns the Message field value
func (o *PrintMessageInStatusSpec) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *PrintMessageInStatusSpec) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.message, true
}

// Message sets field value
func (o *PrintMessageInStatusSpec) Message(v string) *PrintMessageInStatusSpec {
	o.message = v
    return o
}

func (o PrintMessageInStatusSpec) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrintMessageInStatusSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.message
	return toSerialize, nil
}

type NullablePrintMessageInStatusSpec struct {
	value *PrintMessageInStatusSpec
	isSet bool
}

func (v NullablePrintMessageInStatusSpec) Get() *PrintMessageInStatusSpec {
	return v.value
}

func (v *NullablePrintMessageInStatusSpec) Set(val *PrintMessageInStatusSpec) {
	v.value = val
	v.isSet = true
}

func (v NullablePrintMessageInStatusSpec) IsSet() bool {
	return v.isSet
}

func (v *NullablePrintMessageInStatusSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrintMessageInStatusSpec(val *PrintMessageInStatusSpec) *NullablePrintMessageInStatusSpec {
	return &NullablePrintMessageInStatusSpec{value: val, isSet: true}
}

func (v NullablePrintMessageInStatusSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrintMessageInStatusSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

 
