/*
Generated by cue.

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: no version
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package startup_probe

import (
	"encoding/json"

	"vela-go-sdk/apis/utils"
)

// checks if the StartupProbeSpecOneOf type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &StartupProbeSpecOneOf{}

// StartupProbeSpecOneOf struct for StartupProbeSpecOneOf
type StartupProbeSpecOneOf struct {
	// Specify the startup probe for multiple containers
	probes []StartupProbeParams `json:"probes"`
}

// NewStartupProbeSpecOneOfWith instantiates a new StartupProbeSpecOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStartupProbeSpecOneOfWith(probes []StartupProbeParams) *StartupProbeSpecOneOf {
	this := StartupProbeSpecOneOf{}
	this.probes = probes
	return &this
}

// NewStartupProbeSpecOneOf instantiates a new StartupProbeSpecOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStartupProbeSpecOneOf() *StartupProbeSpecOneOf {
	this := StartupProbeSpecOneOf{}
	return &this
}

// GetProbes returns the Probes field value
func (o *StartupProbeSpecOneOf) GetProbes() []StartupProbeParams {
	if o == nil {
		var ret []StartupProbeParams
		return ret
	}

	return o.probes
}

// GetProbesOk returns a tuple with the Probes field value
// and a boolean to check if the value has been set.
func (o *StartupProbeSpecOneOf) GetProbesOk() ([]StartupProbeParams, bool) {
	if o == nil {
		return nil, false
	}
	return o.probes, true
}

// Probes sets field value
func (o *StartupProbeSpecOneOf) Probes(v []StartupProbeParams) *StartupProbeSpecOneOf {
	o.probes = v
	return o
}

func (o StartupProbeSpecOneOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StartupProbeSpecOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["probes"] = o.probes
	return toSerialize, nil
}

type NullableStartupProbeSpecOneOf struct {
	value *StartupProbeSpecOneOf
	isSet bool
}

func (v NullableStartupProbeSpecOneOf) Get() *StartupProbeSpecOneOf {
	return v.value
}

func (v *NullableStartupProbeSpecOneOf) Set(val *StartupProbeSpecOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableStartupProbeSpecOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableStartupProbeSpecOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStartupProbeSpecOneOf(val *StartupProbeSpecOneOf) *NullableStartupProbeSpecOneOf {
	return &NullableStartupProbeSpecOneOf{value: val, isSet: true}
}

func (v NullableStartupProbeSpecOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStartupProbeSpecOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
