/*
Generated by cue.

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: no version
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package suspend

import (
	"encoding/json"

	"github.com/oam-dev/kubevela-core-api/apis/core.oam.dev/common"
	"github.com/oam-dev/kubevela-core-api/pkg/oam/util"

	"vela-go-sdk/api"
	"vela-go-sdk/apis/utils"
)

// checks if the SuspendSpec type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &SuspendSpec{}

// SuspendSpec struct for SuspendSpec
type SuspendSpec struct {
	// Specify the wait duration time to resume workflow such as \"30s\", \"1min\" or \"2m15s\"
	duration *string `json:"duration,omitempty"`
}

// NewSuspendSpecWith instantiates a new SuspendSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSuspendSpecWith() *SuspendSpec {
	this := SuspendSpec{}
	return &this
}

// NewSuspendSpec instantiates a new SuspendSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSuspendSpec() *SuspendSpec {
	this := SuspendSpec{}
	return &this
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *SuspendWorkflowStep) GetDuration() string {
	if o == nil || utils.IsNil(o.Properties.duration) {
		var ret string
		return ret
	}
	return *o.Properties.duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SuspendWorkflowStep) GetDurationOk() (*string, bool) {
	if o == nil || utils.IsNil(o.Properties.duration) {
		return nil, false
	}
	return o.Properties.duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *SuspendWorkflowStep) HasDuration() bool {
	if o != nil && !utils.IsNil(o.Properties.duration) {
		return true
	}

	return false
}

// Duration gets a reference to the given string and assigns it to the duration field.
// duration:  Specify the wait duration time to resume workflow such as \"30s\", \"1min\" or \"2m15s\"
func (o *SuspendWorkflowStep) Duration(v string) *SuspendWorkflowStep {
	o.Properties.duration = &v
	return o
}

func (o SuspendSpec) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SuspendSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.duration) {
		toSerialize["duration"] = o.duration
	}
	return toSerialize, nil
}

type NullableSuspendSpec struct {
	value *SuspendSpec
	isSet bool
}

func (v NullableSuspendSpec) Get() *SuspendSpec {
	return v.value
}

func (v *NullableSuspendSpec) Set(val *SuspendSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableSuspendSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableSuspendSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSuspendSpec(val *SuspendSpec) *NullableSuspendSpec {
	return &NullableSuspendSpec{value: val, isSet: true}
}

func (v NullableSuspendSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSuspendSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

const SuspendType = "suspend"

type SuspendWorkflowStep struct {
	Base       api.WorkflowStepBase
	Properties SuspendSpec
}

func Suspend() *SuspendWorkflowStep {
	s := &SuspendWorkflowStep{Base: api.WorkflowStepBase{}}
	return s
}

func (s *SuspendWorkflowStep) Build() common.WorkflowStep {
	res := common.WorkflowStep{
		Properties: util.Object2RawExtension(s.Properties),
		Type:       SuspendType,
	}
	return res
}

func (s *SuspendWorkflowStep) Props() *SuspendSpec {
	return &s.Properties
}
