/*
Generated by cue.

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: no version
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package notification

import (
	"encoding/json"

	"vela-go-sdk/apis/utils"
)

// checks if the NotificationSpecDingdingUrlOneOf type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &NotificationSpecDingdingUrlOneOf{}

// NotificationSpecDingdingUrlOneOf struct for NotificationSpecDingdingUrlOneOf
type NotificationSpecDingdingUrlOneOf struct {
	// the url address content in string
	value string `json:"value"`
}

// NotificationSpecDingdingUrlOneOfWith instantiates a new NotificationSpecDingdingUrlOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NotificationSpecDingdingUrlOneOfWith(value string) *NotificationSpecDingdingUrlOneOf {
	this := NotificationSpecDingdingUrlOneOf{}
	this.value = value
	return &this
}

// NewNotificationSpecDingdingUrlOneOf instantiates a new NotificationSpecDingdingUrlOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNotificationSpecDingdingUrlOneOf() *NotificationSpecDingdingUrlOneOf {
	this := NotificationSpecDingdingUrlOneOf{}
	return &this
}

// GetValue returns the Value field value
func (o *NotificationSpecDingdingUrlOneOf) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *NotificationSpecDingdingUrlOneOf) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.value, true
}

// Value sets field value
func (o *NotificationSpecDingdingUrlOneOf) Value(v string) *NotificationSpecDingdingUrlOneOf {
	o.value = v
	return o
}

func (o NotificationSpecDingdingUrlOneOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NotificationSpecDingdingUrlOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["value"] = o.value
	return toSerialize, nil
}

type NullableNotificationSpecDingdingUrlOneOf struct {
	value *NotificationSpecDingdingUrlOneOf
	isSet bool
}

func (v NullableNotificationSpecDingdingUrlOneOf) Get() *NotificationSpecDingdingUrlOneOf {
	return v.value
}

func (v *NullableNotificationSpecDingdingUrlOneOf) Set(val *NotificationSpecDingdingUrlOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableNotificationSpecDingdingUrlOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableNotificationSpecDingdingUrlOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotificationSpecDingdingUrlOneOf(val *NotificationSpecDingdingUrlOneOf) *NullableNotificationSpecDingdingUrlOneOf {
	return &NullableNotificationSpecDingdingUrlOneOf{value: val, isSet: true}
}

func (v NullableNotificationSpecDingdingUrlOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotificationSpecDingdingUrlOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
