/*
Generated by cue.

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: no version
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package notification

import (
	"encoding/json"

	"fmt"
	"vela-go-sdk/apis/utils"
)

// NotificationSpecDingdingUrl - Specify the the dingding url, you can either sepcify it in value or use secretRef
type NotificationSpecDingdingUrl struct {
	NotificationSpecDingdingUrlOneOf  *NotificationSpecDingdingUrlOneOf
	NotificationSpecDingdingUrlOneOf1 *NotificationSpecDingdingUrlOneOf1
}

// NotificationSpecDingdingUrlOneOfAsNotificationSpecDingdingUrl is a convenience function that returns NotificationSpecDingdingUrlOneOf wrapped in NotificationSpecDingdingUrl
func NotificationSpecDingdingUrlOneOfAsNotificationSpecDingdingUrl(v *NotificationSpecDingdingUrlOneOf) NotificationSpecDingdingUrl {
	return NotificationSpecDingdingUrl{
		NotificationSpecDingdingUrlOneOf: v,
	}
}

// NotificationSpecDingdingUrlOneOf1AsNotificationSpecDingdingUrl is a convenience function that returns NotificationSpecDingdingUrlOneOf1 wrapped in NotificationSpecDingdingUrl
func NotificationSpecDingdingUrlOneOf1AsNotificationSpecDingdingUrl(v *NotificationSpecDingdingUrlOneOf1) NotificationSpecDingdingUrl {
	return NotificationSpecDingdingUrl{
		NotificationSpecDingdingUrlOneOf1: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *NotificationSpecDingdingUrl) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into NotificationSpecDingdingUrlOneOf
	err = utils.NewStrictDecoder(data).Decode(&dst.NotificationSpecDingdingUrlOneOf)
	if err == nil {
		jsonNotificationSpecDingdingUrlOneOf, _ := json.Marshal(dst.NotificationSpecDingdingUrlOneOf)
		if string(jsonNotificationSpecDingdingUrlOneOf) == "{}" { // empty struct
			dst.NotificationSpecDingdingUrlOneOf = nil
		} else {
			match++
		}
	} else {
		dst.NotificationSpecDingdingUrlOneOf = nil
	}

	// try to unmarshal data into NotificationSpecDingdingUrlOneOf1
	err = utils.NewStrictDecoder(data).Decode(&dst.NotificationSpecDingdingUrlOneOf1)
	if err == nil {
		jsonNotificationSpecDingdingUrlOneOf1, _ := json.Marshal(dst.NotificationSpecDingdingUrlOneOf1)
		if string(jsonNotificationSpecDingdingUrlOneOf1) == "{}" { // empty struct
			dst.NotificationSpecDingdingUrlOneOf1 = nil
		} else {
			match++
		}
	} else {
		dst.NotificationSpecDingdingUrlOneOf1 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.NotificationSpecDingdingUrlOneOf = nil
		dst.NotificationSpecDingdingUrlOneOf1 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(NotificationSpecDingdingUrl)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(NotificationSpecDingdingUrl)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src NotificationSpecDingdingUrl) MarshalJSON() ([]byte, error) {
	if src.NotificationSpecDingdingUrlOneOf != nil {
		return json.Marshal(&src.NotificationSpecDingdingUrlOneOf)
	}

	if src.NotificationSpecDingdingUrlOneOf1 != nil {
		return json.Marshal(&src.NotificationSpecDingdingUrlOneOf1)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *NotificationSpecDingdingUrl) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.NotificationSpecDingdingUrlOneOf != nil {
		return obj.NotificationSpecDingdingUrlOneOf
	}

	if obj.NotificationSpecDingdingUrlOneOf1 != nil {
		return obj.NotificationSpecDingdingUrlOneOf1
	}

	// all schemas are nil
	return nil
}

type NullableNotificationSpecDingdingUrl struct {
	value *NotificationSpecDingdingUrl
	isSet bool
}

func (v NullableNotificationSpecDingdingUrl) Get() *NotificationSpecDingdingUrl {
	return v.value
}

func (v *NullableNotificationSpecDingdingUrl) Set(val *NotificationSpecDingdingUrl) {
	v.value = val
	v.isSet = true
}

func (v NullableNotificationSpecDingdingUrl) IsSet() bool {
	return v.isSet
}

func (v *NullableNotificationSpecDingdingUrl) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotificationSpecDingdingUrl(val *NotificationSpecDingdingUrl) *NullableNotificationSpecDingdingUrl {
	return &NullableNotificationSpecDingdingUrl{value: val, isSet: true}
}

func (v NullableNotificationSpecDingdingUrl) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotificationSpecDingdingUrl) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
