/*
Generated by cue.

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: no version
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package webservice

import (
"encoding/json"
. "vela-go-sdk/api"
"vela-go-sdk/apis/utils"

"github.com/oam-dev/kubevela-core-api/apis/core.oam.dev/common"
"github.com/oam-dev/kubevela-core-api/pkg/oam/util"
)



    
    // checks if the WebserviceSpecVolumeMountsConfigMap type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &WebserviceSpecVolumeMountsConfigMap{}

// WebserviceSpecVolumeMountsConfigMap struct for WebserviceSpecVolumeMountsConfigMap
type WebserviceSpecVolumeMountsConfigMap struct {
	cmName string `json:"cmName"`
	defaultMode int32 `json:"defaultMode"`
	items []WebserviceSpecVolumeMountsConfigMapItems `json:"items,omitempty"`
	mountPath string `json:"mountPath"`
	name string `json:"name"`
	subPath *string `json:"subPath,omitempty"`
}

// NewWebserviceSpecVolumeMountsConfigMap instantiates a new WebserviceSpecVolumeMountsConfigMap object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebserviceSpecVolumeMountsConfigMap(cmName string, defaultMode int32, mountPath string, name string) *WebserviceSpecVolumeMountsConfigMap {
	this := WebserviceSpecVolumeMountsConfigMap{}
	this.cmName = cmName
	this.defaultMode = defaultMode
	this.mountPath = mountPath
	this.name = name
	return &this
}

// NewWebserviceSpecVolumeMountsConfigMapWithDefaults instantiates a new WebserviceSpecVolumeMountsConfigMap object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebserviceSpecVolumeMountsConfigMapWithDefaults() *WebserviceSpecVolumeMountsConfigMap {
	this := WebserviceSpecVolumeMountsConfigMap{}
	var defaultMode int32 = 420
	this.defaultMode = defaultMode
	return &this
}

// GetCmName returns the CmName field value
func (o *WebserviceSpecVolumeMountsConfigMap) GetCmName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.cmName
}

// GetCmNameOk returns a tuple with the CmName field value
// and a boolean to check if the value has been set.
func (o *WebserviceSpecVolumeMountsConfigMap) GetCmNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.cmName, true
}

// CmName sets field value
func (o *WebserviceSpecVolumeMountsConfigMap) CmName(v string) *WebserviceSpecVolumeMountsConfigMap {
	o.cmName = v
    return o
}

// GetDefaultMode returns the DefaultMode field value
func (o *WebserviceSpecVolumeMountsConfigMap) GetDefaultMode() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.defaultMode
}

// GetDefaultModeOk returns a tuple with the DefaultMode field value
// and a boolean to check if the value has been set.
func (o *WebserviceSpecVolumeMountsConfigMap) GetDefaultModeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.defaultMode, true
}

// DefaultMode sets field value
func (o *WebserviceSpecVolumeMountsConfigMap) DefaultMode(v int32) *WebserviceSpecVolumeMountsConfigMap {
	o.defaultMode = v
    return o
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *WebserviceSpecVolumeMountsConfigMap) GetItems() []WebserviceSpecVolumeMountsConfigMapItems {
	if o == nil || utils.IsNil(o.items) {
		var ret []WebserviceSpecVolumeMountsConfigMapItems
		return ret
	}
	return o.items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebserviceSpecVolumeMountsConfigMap) GetItemsOk() ([]WebserviceSpecVolumeMountsConfigMapItems, bool) {
	if o == nil || utils.IsNil(o.items) {
		return nil, false
	}
	return o.items, true
}

// HasItems returns a boolean if a field has been set.
func (o *WebserviceSpecVolumeMountsConfigMap) HasItems() bool {
	if o != nil && !utils.IsNil(o.items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []WebserviceSpecVolumeMountsConfigMapItems and assigns it to the items field.
// items: 

func (o *WebserviceSpecVolumeMountsConfigMap) Items(v []WebserviceSpecVolumeMountsConfigMapItems) (*WebserviceSpecVolumeMountsConfigMap){
	o.items = v
return o
}

// GetMountPath returns the MountPath field value
func (o *WebserviceSpecVolumeMountsConfigMap) GetMountPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.mountPath
}

// GetMountPathOk returns a tuple with the MountPath field value
// and a boolean to check if the value has been set.
func (o *WebserviceSpecVolumeMountsConfigMap) GetMountPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.mountPath, true
}

// MountPath sets field value
func (o *WebserviceSpecVolumeMountsConfigMap) MountPath(v string) *WebserviceSpecVolumeMountsConfigMap {
	o.mountPath = v
    return o
}

// GetName returns the Name field value
func (o *WebserviceSpecVolumeMountsConfigMap) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *WebserviceSpecVolumeMountsConfigMap) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.name, true
}

// Name sets field value
func (o *WebserviceSpecVolumeMountsConfigMap) Name(v string) *WebserviceSpecVolumeMountsConfigMap {
	o.name = v
    return o
}

// GetSubPath returns the SubPath field value if set, zero value otherwise.
func (o *WebserviceSpecVolumeMountsConfigMap) GetSubPath() string {
	if o == nil || utils.IsNil(o.subPath) {
		var ret string
		return ret
	}
	return *o.subPath
}

// GetSubPathOk returns a tuple with the SubPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebserviceSpecVolumeMountsConfigMap) GetSubPathOk() (*string, bool) {
	if o == nil || utils.IsNil(o.subPath) {
		return nil, false
	}
	return o.subPath, true
}

// HasSubPath returns a boolean if a field has been set.
func (o *WebserviceSpecVolumeMountsConfigMap) HasSubPath() bool {
	if o != nil && !utils.IsNil(o.subPath) {
		return true
	}

	return false
}

// SetSubPath gets a reference to the given string and assigns it to the subPath field.
// subPath: 

func (o *WebserviceSpecVolumeMountsConfigMap) SubPath(v string) (*WebserviceSpecVolumeMountsConfigMap){
	o.subPath = &v
return o
}

func (o WebserviceSpecVolumeMountsConfigMap) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebserviceSpecVolumeMountsConfigMap) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cmName"] = o.cmName
	toSerialize["defaultMode"] = o.defaultMode
	if !utils.IsNil(o.items) {
		toSerialize["items"] = o.items
	}
	toSerialize["mountPath"] = o.mountPath
	toSerialize["name"] = o.name
	if !utils.IsNil(o.subPath) {
		toSerialize["subPath"] = o.subPath
	}
	return toSerialize, nil
}

type NullableWebserviceSpecVolumeMountsConfigMap struct {
	value *WebserviceSpecVolumeMountsConfigMap
	isSet bool
}

func (v NullableWebserviceSpecVolumeMountsConfigMap) Get() *WebserviceSpecVolumeMountsConfigMap {
	return v.value
}

func (v *NullableWebserviceSpecVolumeMountsConfigMap) Set(val *WebserviceSpecVolumeMountsConfigMap) {
	v.value = val
	v.isSet = true
}

func (v NullableWebserviceSpecVolumeMountsConfigMap) IsSet() bool {
	return v.isSet
}

func (v *NullableWebserviceSpecVolumeMountsConfigMap) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebserviceSpecVolumeMountsConfigMap(val *WebserviceSpecVolumeMountsConfigMap) *NullableWebserviceSpecVolumeMountsConfigMap {
	return &NullableWebserviceSpecVolumeMountsConfigMap{value: val, isSet: true}
}

func (v NullableWebserviceSpecVolumeMountsConfigMap) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebserviceSpecVolumeMountsConfigMap) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

 
