/*
Generated by cue.

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: no version
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resource

import (
	"encoding/json"
	"vela-go-sdk/pkg/apis/utils"
)

// checks if the Limits type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Limits{}

// Limits Specify the resources in limits
type Limits struct {
	// Specify the amount of cpu for limits
	cpu float32 `json:"cpu"`
	// Specify the amount of memory for limits
	memory string `json:"memory"`
}

// NewLimitsWith instantiates a new Limits object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLimitsWith(cpu float32, memory string) *Limits {
	this := Limits{}
	this.cpu = cpu
	this.memory = memory
	return &this
}

// NewLimits instantiates a new Limits object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLimits() *Limits {
	this := Limits{}
	var cpu float32 = 1
	this.cpu = cpu
	var memory string = "2048Mi"
	this.memory = memory
	return &this
}

// GetCpu returns the Cpu field value
func (o *Limits) GetCpu() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.cpu
}

// GetCpuOk returns a tuple with the Cpu field value
// and a boolean to check if the value has been set.
func (o *Limits) GetCpuOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.cpu, true
}

// Cpu sets field value
func (o *Limits) Cpu(v float32) *Limits {
	o.cpu = v
	return o
}

// GetMemory returns the Memory field value
func (o *Limits) GetMemory() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.memory
}

// GetMemoryOk returns a tuple with the Memory field value
// and a boolean to check if the value has been set.
func (o *Limits) GetMemoryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.memory, true
}

// Memory sets field value
func (o *Limits) Memory(v string) *Limits {
	o.memory = v
	return o
}

func (o Limits) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Limits) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cpu"] = o.cpu
	toSerialize["memory"] = o.memory
	return toSerialize, nil
}

type NullableLimits struct {
	value *Limits
	isSet bool
}

func (v NullableLimits) Get() *Limits {
	return v.value
}

func (v *NullableLimits) Set(val *Limits) {
	v.value = val
	v.isSet = true
}

func (v NullableLimits) IsSet() bool {
	return v.isSet
}

func (v *NullableLimits) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLimits(val *Limits) *NullableLimits {
	return &NullableLimits{value: val, isSet: true}
}

func (v NullableLimits) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLimits) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
