/*
Generated by cue.

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: no version
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package print_message_in_status

import (
	"encoding/json"

	"github.com/oam-dev/kubevela-core-api/apis/core.oam.dev/common"
	"github.com/oam-dev/kubevela-core-api/apis/core.oam.dev/v1beta1"
	"github.com/oam-dev/kubevela-core-api/pkg/oam/util"

	"github.com/chivalryq/vela-go-sdk/pkg/apis"
	"github.com/chivalryq/vela-go-sdk/pkg/apis/utils"
)

// checks if the PrintMessageInStatusSpec type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &PrintMessageInStatusSpec{}

// PrintMessageInStatusSpec struct for PrintMessageInStatusSpec
type PrintMessageInStatusSpec struct {
	message string `json:"message"`
}

// NewPrintMessageInStatusSpecWith instantiates a new PrintMessageInStatusSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrintMessageInStatusSpecWith(message string) *PrintMessageInStatusSpec {
	this := PrintMessageInStatusSpec{}
	this.message = message
	return &this
}

// NewPrintMessageInStatusSpec instantiates a new PrintMessageInStatusSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrintMessageInStatusSpec() *PrintMessageInStatusSpec {
	this := PrintMessageInStatusSpec{}
	return &this
}

// GetMessage returns the Message field value
func (o *PrintMessageInStatusWorkflowStep) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Properties.message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *PrintMessageInStatusWorkflowStep) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Properties.message, true
}

// Message sets field value
func (o *PrintMessageInStatusWorkflowStep) Message(v string) *PrintMessageInStatusWorkflowStep {
	o.Properties.message = v
	return o
}

func (o PrintMessageInStatusSpec) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrintMessageInStatusSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.message
	return toSerialize, nil
}

type NullablePrintMessageInStatusSpec struct {
	value *PrintMessageInStatusSpec
	isSet bool
}

func (v NullablePrintMessageInStatusSpec) Get() *PrintMessageInStatusSpec {
	return v.value
}

func (v *NullablePrintMessageInStatusSpec) Set(val *PrintMessageInStatusSpec) {
	v.value = val
	v.isSet = true
}

func (v NullablePrintMessageInStatusSpec) IsSet() bool {
	return v.isSet
}

func (v *NullablePrintMessageInStatusSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrintMessageInStatusSpec(val *PrintMessageInStatusSpec) *NullablePrintMessageInStatusSpec {
	return &NullablePrintMessageInStatusSpec{value: val, isSet: true}
}

func (v NullablePrintMessageInStatusSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrintMessageInStatusSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

const PrintMessageInStatusType = "print-message-in-status"

type PrintMessageInStatusWorkflowStep struct {
	Base       apis.WorkflowStepBase
	Properties PrintMessageInStatusSpec
}

func PrintMessageInStatus(name string) *PrintMessageInStatusWorkflowStep {
	p := &PrintMessageInStatusWorkflowStep{Base: apis.WorkflowStepBase{
		Name: name,
	}}
	return p
}

func (p *PrintMessageInStatusWorkflowStep) Build() v1beta1.WorkflowStep {
	_subSteps := make([]v1beta1.WorkflowStep, 0)
	for _, subStep := range p.Base.SubSteps {
		_subSteps = append(_subSteps, subStep.Build())
	}
	subSteps := make([]common.WorkflowSubStep, 0)
	for _, _s := range _subSteps {
		subSteps = append(subSteps, common.WorkflowSubStep{Name: _s.Name, DependsOn: _s.DependsOn, Inputs: _s.Inputs, Outputs: _s.Outputs, If: _s.If, Timeout: _s.Timeout, Meta: _s.Meta, Properties: _s.Properties})
	}
	res := v1beta1.WorkflowStep{
		DependsOn:  p.Base.DependsOn,
		If:         p.Base.If,
		Inputs:     p.Base.Inputs,
		Meta:       p.Base.Meta,
		Name:       p.Base.Name,
		Outputs:    p.Base.Outputs,
		Properties: util.Object2RawExtension(p.Properties),
		SubSteps:   subSteps,
		Timeout:    p.Base.Timeout,
		Type:       PrintMessageInStatusType,
	}
	return res
}

func (p *PrintMessageInStatusWorkflowStep) If(_if string) *PrintMessageInStatusWorkflowStep {
	p.Base.If = _if
	return p
}

func (p *PrintMessageInStatusWorkflowStep) Alias(alias string) *PrintMessageInStatusWorkflowStep {
	p.Base.Meta.Alias = alias
	return p
}

func (p *PrintMessageInStatusWorkflowStep) Timeout(timeout string) *PrintMessageInStatusWorkflowStep {
	p.Base.Timeout = timeout
	return p
}

func (p *PrintMessageInStatusWorkflowStep) DependsOn(dependsOn []string) *PrintMessageInStatusWorkflowStep {
	p.Base.DependsOn = dependsOn
	return p
}

func (p *PrintMessageInStatusWorkflowStep) Inputs(input common.StepInputs) *PrintMessageInStatusWorkflowStep {
	p.Base.Inputs = input
	return p
}

func (p *PrintMessageInStatusWorkflowStep) Outputs(output common.StepOutputs) *PrintMessageInStatusWorkflowStep {
	p.Base.Outputs = output
	return p
}

func (p *PrintMessageInStatusWorkflowStep) Name() string {
	return p.Base.Name
}

func (p *PrintMessageInStatusWorkflowStep) Type() string {
	return PrintMessageInStatusType
}
