/*
Generated by cue.

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: no version
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package webservice

import (
	"encoding/json"

	"github.com/chivalryq/vela-go-sdk/pkg/apis/utils"
)

// checks if the Pvc type satisfies the MappedNullable interface at compile time
var _ utils.MappedNullable = &Pvc{}

// Pvc struct for Pvc
type Pvc struct {
	// The name of the PVC
	claimName *string `json:"claimName,omitempty"`
	mountPath *string `json:"mountPath,omitempty"`
	name      *string `json:"name,omitempty"`
	subPath   *string `json:"subPath,omitempty"`
}

// NewPvcWith instantiates a new Pvc object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPvcWith() *Pvc {
	this := Pvc{}
	return &this
}

// NewPvc instantiates a new Pvc object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPvc() *Pvc {
	this := Pvc{}
	return &this
}

// GetClaimName returns the ClaimName field value if set, zero value otherwise.
func (o *Pvc) GetClaimName() string {
	if o == nil || utils.IsNil(o.claimName) {
		var ret string
		return ret
	}
	return *o.claimName
}

// GetClaimNameOk returns a tuple with the ClaimName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Pvc) GetClaimNameOk() (*string, bool) {
	if o == nil || utils.IsNil(o.claimName) {
		return nil, false
	}
	return o.claimName, true
}

// HasClaimName returns a boolean if a field has been set.
func (o *Pvc) HasClaimName() bool {
	if o != nil && !utils.IsNil(o.claimName) {
		return true
	}

	return false
}

// ClaimName gets a reference to the given string and assigns it to the claimName field.
// claimName:  The name of the PVC
func (o *Pvc) ClaimName(v string) *Pvc {
	o.claimName = &v
	return o
}

// GetMountPath returns the MountPath field value if set, zero value otherwise.
func (o *Pvc) GetMountPath() string {
	if o == nil || utils.IsNil(o.mountPath) {
		var ret string
		return ret
	}
	return *o.mountPath
}

// GetMountPathOk returns a tuple with the MountPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Pvc) GetMountPathOk() (*string, bool) {
	if o == nil || utils.IsNil(o.mountPath) {
		return nil, false
	}
	return o.mountPath, true
}

// HasMountPath returns a boolean if a field has been set.
func (o *Pvc) HasMountPath() bool {
	if o != nil && !utils.IsNil(o.mountPath) {
		return true
	}

	return false
}

// MountPath gets a reference to the given string and assigns it to the mountPath field.
// mountPath:
func (o *Pvc) MountPath(v string) *Pvc {
	o.mountPath = &v
	return o
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Pvc) GetName() string {
	if o == nil || utils.IsNil(o.name) {
		var ret string
		return ret
	}
	return *o.name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Pvc) GetNameOk() (*string, bool) {
	if o == nil || utils.IsNil(o.name) {
		return nil, false
	}
	return o.name, true
}

// HasName returns a boolean if a field has been set.
func (o *Pvc) HasName() bool {
	if o != nil && !utils.IsNil(o.name) {
		return true
	}

	return false
}

// Name gets a reference to the given string and assigns it to the name field.
// name:
func (o *Pvc) Name(v string) *Pvc {
	o.name = &v
	return o
}

// GetSubPath returns the SubPath field value if set, zero value otherwise.
func (o *Pvc) GetSubPath() string {
	if o == nil || utils.IsNil(o.subPath) {
		var ret string
		return ret
	}
	return *o.subPath
}

// GetSubPathOk returns a tuple with the SubPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Pvc) GetSubPathOk() (*string, bool) {
	if o == nil || utils.IsNil(o.subPath) {
		return nil, false
	}
	return o.subPath, true
}

// HasSubPath returns a boolean if a field has been set.
func (o *Pvc) HasSubPath() bool {
	if o != nil && !utils.IsNil(o.subPath) {
		return true
	}

	return false
}

// SubPath gets a reference to the given string and assigns it to the subPath field.
// subPath:
func (o *Pvc) SubPath(v string) *Pvc {
	o.subPath = &v
	return o
}

func (o Pvc) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Pvc) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.claimName) {
		toSerialize["claimName"] = o.claimName
	}
	if !utils.IsNil(o.mountPath) {
		toSerialize["mountPath"] = o.mountPath
	}
	if !utils.IsNil(o.name) {
		toSerialize["name"] = o.name
	}
	if !utils.IsNil(o.subPath) {
		toSerialize["subPath"] = o.subPath
	}
	return toSerialize, nil
}

type NullablePvc struct {
	value *Pvc
	isSet bool
}

func (v NullablePvc) Get() *Pvc {
	return v.value
}

func (v *NullablePvc) Set(val *Pvc) {
	v.value = val
	v.isSet = true
}

func (v NullablePvc) IsSet() bool {
	return v.isSet
}

func (v *NullablePvc) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePvc(val *Pvc) *NullablePvc {
	return &NullablePvc{value: val, isSet: true}
}

func (v NullablePvc) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePvc) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
